### ISSUE TITLE
Saving reordered path output

### ISSUE THREAD

**Issue by pzich** [evil-mad/axidraw#101]
At a high level, I am looking to essentially run the reordering that `ad.options.reordering = 3` does and save the output to a file so that I can run it later without having to wait for the reordering again. I thought that saving the output of `ad.plot_run(True)` with `ad.options.reordering = 3` would do this, but when I run the estimate with the output file it seems to use the original pathing. To test this I used the following code to run an intentionally inefficiently-pathed SVG as a test file.
```python
import sys
from pyaxidraw import axidraw

input_file = sys.argv[2]
output_file = sys.argv[3]

ad = axidraw.AxiDraw()
ad.plot_setup(input_file)
ad.options.auto_rotate = False
ad.options.report_time = True
ad.options.preview = True
ad.options.reordering = int(sys.argv[1])

output_svg = ad.plot_run(True)
f = open(output_file, "w")
f.write(output_svg)
f.close()
```
And below is the console output
```
$ python3 pather.py 0 a.svg tmp.svg
Estimated print time: 14:24 (minutes, seconds)
Length of path to draw: 9.75 m.
Pen-up travel distance: 49.83 m.
Total movement distance: 59.58 m.
This estimate took: 0:00:00 (Hours, minutes, seconds)

$ python3 pather.py 3 a.svg b.svg  
Estimated print time: 09:41 (minutes, seconds)
Length of path to draw: 9.75 m.
Pen-up travel distance: 10.10 m.
Total movement distance: 19.85 m.
This estimate took: 0:00:00 (Hours, minutes, seconds)

$ python3 pather.py 0 b.svg c.svg
Estimated print time: 14:24 (minutes, seconds)
Length of path to draw: 9.75 m.
Pen-up travel distance: 49.83 m.
Total movement distance: 59.58 m.
This estimate took: 0:00:00 (Hours, minutes, seconds)
```
I would expect `python3 pather.py 3 a.svg b.svg` to generate a reordered SVG `b.svg` and that running this through the pather with `reorder = 0` would use that optimized path, but instead it produces the same result as the original file without reordering. Is this expected behavior? I also tried using `mode = "res_plot"` on the output but it says `No in-progress plot data found in file.`

**Comment by oskay** [comment]
Without addressing the main question, is it the case that these estimates each took "0:00:00 (Hours, minutes, seconds)"? Or, is it the case that there is an issue here, and these time estimates are inaccurate?

**Comment by oskay** [comment]
When I test like this, I'm definitely getting some non-zero computation time:
```
python3 pather.py 3 cat-stipple2.svg out.svg
Estimated print time: 2:19:34 (Hours, minutes, seconds)
Length of path to draw: 104.37 m.
Pen-up travel distance: 40.41 m.
Total movement distance: 144.78 m.
This estimate took: 0:00:37 (Hours, minutes, seconds)
```

That may just be because my computer is older and slower than yours. However, if these computations are really taking 0:00:00 on your computer, then (to answer your "high level" concern) there is no time savings to be had by running optimization only once. 

(If that is not the case -- and they are taking some time but not reporting it -- I would appreciate confirmation of that issue and any additional data that might be helpful in trying to replicate it.)

> I would expect python3 pather.py 3 a.svg b.svg to generate a reordered SVG b.svg and that running this through the pather with reorder = 0 would use that optimized path, but instead it produces the same result as the original file without reordering. Is this expected behavior? 

Yes, this is expected (and intentional) behavior. This Plot Optimization option is the same as that in the Inkscape-based software. From the user guide, "Any changes made to the order of elements in the file by the Plot optimization feature are _ephemeral_. A temporary copy of the file is created, re-ordered, and then plotted; no changes to the order of elements in your file are retained." We will make a note to improve the python API documentation to make this clear.

There is a separate Plot Optimization extension available in Inkscape, which does save the reordered file (and does not plot). The AxiDraw CLI does support this option as well, called [reorder mode](https://axidraw.com/doc/cli_api/#reorder), but it is not available through the python API at present. There are major changes to the reordering strategies underway at present, and we are planning to add a similar option to the python API when those changes are implemented.

>  I also tried using mode = "res_plot" on the output but it says No in-progress plot data found in file.

This is also as expected. A plot that was not interrupted cannot be resumed.

**Comment by pzich** [comment]
Whoops sorry for the delay. I didn't get notified about a response here!

> Without addressing the main question, is it the case that these estimates each took "0:00:00 (Hours, minutes, seconds)"? Or, is it the case that there is an issue here, and these time estimates are inaccurate?

In this case yes they were very quick, it was a very simple file just to illustrate the difference in path time. Some of the more complex SVGs I have take more than 6 minutes to optimize, so I'm hoping to be able to do that in advance so it's faster to plot in subsequent runs, as shown below.

```
$ python3 pather.py 0 a.svg tmp.svg
Estimated print time: 7:30:29 (Hours, minutes, seconds)
Length of path to draw: 131.86 m.
Pen-up travel distance: 1060.72 m.
Total movement distance: 1192.58 m.
This estimate took: 0:00:15 (Hours, minutes, seconds)

$ python3 pather.py 3 a.svg b.svg 
Estimated print time: 4:30:08 (Hours, minutes, seconds)
Length of path to draw: 131.99 m.
Pen-up travel distance: 71.15 m.
Total movement distance: 203.14 m.
This estimate took: 0:06:31 (Hours, minutes, seconds)

$ python3 pather.py 0 b.svg c.svg
Estimated print time: 7:30:29 (Hours, minutes, seconds)
Length of path to draw: 131.86 m.
Pen-up travel distance: 1060.72 m.
Total movement distance: 1192.58 m.
This estimate took: 0:00:15 (Hours, minutes, seconds)
```

> The AxiDraw CLI does support this option as well, called reorder mode, but it is not available through the python API at present. There are major changes to the reordering strategies underway at present, and we are planning to add a similar option to the python API when those changes are implemented.

Ahh okay! Great to hear! I will try out the CLI for now.

**Comment by oskay** [comment]
Is this issue resolved?

**Comment by stephanschulz** [comment]
`but it is not available through the python API at present`
Has the option to save the order auto as SVG been added to the Python API?
Thanks a bunch.

**Comment by oskay** [comment]
> Has the option to save the order auto as SVG been added to the Python API?

I'm not sure exactly what you're asking, but the new ordering method is destructive, and neither the Python nor CLI API can save its output at present. We are planning to add support for that at some point.

**Comment by stephanschulz** [comment]
In one of your replies you indicated that at some point the Python API will be able to do what the CLI can already do: Saving reordered path to output SVG file.
For now I am using
`axicli file.svg --mode reorder --reordering 3 -o out.svg`
to get a new file in which I think the paths are reordered / optimized.

**Comment by oskay** [comment]
`reorder` mode is deprecated and will be removed from a future version of the CLI API as well.

**Comment by stephanschulz** [comment]
oh.
What other method would you recommend to use?

**Comment by oskay** [comment]
There will be a new feature that replaces it, once implemented, and before that is removed. Whether or not it will work for your application depends on what your application is.

**Comment by oskay** [comment]
AxiDraw software 3.1, out today, adds an option to output the reordered "plot digest".
