### ISSUE TITLE
Hershey Crashes when used with text box from imported svg

### ISSUE THREAD

**Issue by digitalcoleman** [evil-mad/axidraw#136]
I am creating Text boxes in Affinity Publisher, and exporting svg files. When imported into Inkscape, any text in the text box, even if you change the font or re-type the text, causes Hershey to throw this error: 
```
Traceback (most recent call last):
File "hershey.py", line 1939, in <module>
   Hershey().run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 131, in run
    self.save_raw(self.effect())
  File "hershey.py", line 1893, in effect
    self.handle_viewbox()
  File "hershey.py", line 988, in handle_viewbox
    s_x, s_y, o_x, o_y = self.vb_scale(viewbox, p_a_r, self.svg_width, self.svg_height)
  File "hershey.py", line 348, in vb_scale
    d_width = float(doc_width)
TypeError: float() argument must be a string or a number, not 'NoneType'
```

**Comment by oskay** [comment]
It sounds like your document does not have physical dimensions; consider adding a size to the document so that Hershey Text can process it. Without a physical scale, Hershey Text will not be able to process the document.

I'm closing this issue and adding one in the Hershey Text repository, https://gitlab.com/oskay/hershey-text/-/issues/33

I have not used Affinity Publisher, so I don't know for certain how to generate SVG output from it, nor what output options it has, nor what the output SVG looks like.

I have tested Affinity Designer, for which the "recipe" to successfully output SVG is as follows: In Document Setup, set DPI to 96.  Then, export SVG. In the export dialog, open the More... dialog and then untick 'Set Viewbox'

**Comment by oskay** [comment]
(While the note says "completed", please understand that this issue is *moved*, and still active.)
