### ISSUE TITLE
AxiDraw going beyond size limits during Pause/Resume

### ISSUE THREAD

**Issue by haschdl** [evil-mad/axidraw#149]
I noticed with two different SVG files that pausing and resuming causes the AxiDraw to loose track of its positions. I can only guess but it seems to assume it is located in the home position when it's about to Resume.   I cannot reproduce it consistently, has anyone else reported it?

Model: AxiDraw SE/A3
AxiDraw driver version 3.8.1
AxiDraw firmware version 2.8.1
Inkscape: 1.2.1
OS: MacOS 13.1 Ventura

**Comment by oskay** [comment]
We have not had any other reports of this with the current (or recent) versions.  

That's potentially an extremely serious issue, and it will be our top priority issue if confirmed.

Some things to keep in mind:
* The plot progress and position are saved *in the SVG file*, not in the AxiDraw. If you change which file is loaded, revert the file, or make changes to the file in the middle of the plotting process, it is possible to interfere with the plot and resume process.
* The only standard process by which the saved carriage position can get shifted to Home is when you run the "Resume - Return to Home Corner" command.
* If the plot data were lost or reset such that there were no pause/resume data in the file, it should give the "No in-progress plot data found in file" message, rather than starting from the wrong place.
* One thing that can cause of the symptoms that you describe is starting from the Plot tab, rather than the Resume tab. 

You might consider saving a separate copy of your file before resuming, just in case -- if you can show us the file and how it looks before resuming (potentially with all graphical elements removed), it may be helpful to understand the situation.

**Comment by oskay** [comment]
I'm going to close this since there hasn't been a follow-up, and we haven't heard any further confirmation here or separate reports otherwise. If there is a way to reproduce it -- or if it keeps happening even without a clear way to reproduce it -- let's re-open this.
