### ISSUE TITLE
Predict plot duration

### ISSUE THREAD

**Issue by Daekkyn** [evil-mad/axidraw#27]
It would be very useful to have a feature that predicts how long a plot will take. And similarly, to visualize the trajectory of the pen, for example with a dot the moves along the path, but I'm not sure Inkscape allows for this.

**Comment by oskay** [comment]
While Inkscape does not allow real-time animation, one approach would be to draw lines that represent pen-up moves, thus allowing you to visualize the path reasonably well.

**Comment by oskay** [comment]
As of version 1.4.0, added today, you can use the new preview mode option to estimate how long a plot will take. It's accurate enough to let you see the effects of different plot options (servo speed, plot speed, curvature settings) have on the plot time.

**Comment by oskay** [comment]
v 1.5.0 adds a render preview function that shows the pen-up and pen-down paths.

**Comment by Daekkyn** [comment]
I tested 1.5.2 which works well, thanks.
One suggestion for further improvement would be to add a slider that defines the virtual plot progress. This would allow the user to get a better sense of the ordering of the paths. By use the live preview functionality of Inkscape extension, you would be able to preview whole plot by moving the slider. The option `appearance="full"` can be used to add a slider to a float box ([link](http://wiki.inkscape.org/wiki/index.php/INX_Parameters#Available_types)).

**Comment by oskay** [comment]
We are not planning to bring the live preview capability to the extension. The set of possible interactions gets complicated if there is both live preview and control of external devices.

If representing the order through the plot is the concern, one possibility would be to use variable color on the pen-up preview path (starting red, ending violet), or perhaps to add start and end markers.

(Another possibility would be to separate out the preview capability into a separate Inkscape extension, which would then allow one to run a live preview. However, that is not a universally "better" solution, since it would have a separate set of parameters, and could not directly estimate how long your plot would take, unless you re-entered all of those parameters.)
