### ISSUE TITLE
Feature Request: Compensate Z height as a function of Y position

### ISSUE THREAD

**Issue by simlu** [evil-mad/axidraw#40]
I'm trying to keep the pen lift to an absolute minimum. However the arm bends slightly as it extends. This means when adjusting the UP position to be optimal at the origin, the pen will touch the paper when far away from the origin along the X axis.

__Pen Lift Setup__
![](http://i.imgur.com/6FsRucW.png)

I'm suggesting to add a lift offset value. I.e. add X percent (user defined) when the arm is stretched out all the way and interpolate in between. There are other options to improve this, however this seemed to me the easiest (from implementation, as well as from a user input perspective).

Very happy to discuss!

**Comment by oskay** [comment]
While I understand the issue, I think that this is probably not something that belongs in the general set of features that we want to add to the GUI. It might be acceptable to add as an option that could be adjusted in the configuration file. 

There are a few reasons for this, but the main is that the AxiDraw geometry does not guarantee a consistent height over the page -- one of the reasons that we use a floating Z stage that accommodates variation in both the machine (due to pen weight, position, etc) and paper thickness. 

In general, we would recommend physically shimming either the workholding or the AxiDraw itself-- for example by adding some thin material under the front or rear feet of the easel or AxiDraw if needed.

**Comment by oskay** [comment]
Attached is a calibration plot that can be used to help with leveling. It plots numbers at various pen-down heights.

[Z Cal test.zip](https://github.com/evil-mad/axidraw/files/1236719/Z.Cal.test.zip)

**Comment by simlu** [comment]
Thank you for the Calibration test. It honestly didn't help much. Ideally the scale is a lot finer (maybe one percent?).

`but the main is that the AxiDraw geometry does not guarantee a consistent height over the page` - I would expect this to not vary a lot between different AxiDraw machines and even pen weights. Could we build in a factor by default without exposing it as a setting? Or do you have a good reason not to do this?

**Comment by oskay** [comment]
This does actually vary a lot between different machines, and indeed even with an individual machine with different pen weights. The cantilevered geometry amplifies even very small amounts of bend or twist in the extrusions (X or Y) on AxiDraw V3 or shafts in AxiDraw V2 or in the leveling of the feet in either version. We certainly know enough about calibration of these machines to know that building in a calibration value by default will hurt as many machines as it will help. Additionally, table flatness is frequently a larger factor than this alone.

If you, on your machine, have a consistent degree of pen height change with Y position, it may be the case that you should physically compensate by leveling the front or rear feet as needed.

**Comment by oskay** [comment]
I am closing this for the time being. It may be worth revisiting in the future.

**Comment by simlu** [comment]
Sounds good! I will experiment with fixating the machine soon and then we'll see how much this would actually help. Cheers
