### ISSUE TITLE
Bug: Layers / elements hidden via the UI (which styles the element "display:none") are plotted when they should remain hidden

### ISSUE THREAD

**Issue by MartyMacGyver** [evil-mad/axidraw#49]
Despite hiding SVG layers in the UI or programmatically (via the style "display:none"), they still get plotted by the AxiDraw control. Normal printing excludes such elements.

Two test files are attached... one has all layers visible, the other has a layer hidden via the style "display:none". Both plot exactly the same, despite the layer being hidden.

There is code present that's supposed to deal with visibility on output, but that code doesn't look at the style at all (which is where this information normally resides for files created in Inkscape or Illustrator).

I've submitted PR #47 to correct this issue. It follows the same convention as was used in the current code, including notifying the user with the pre-existing informational box that is already used when hidden/invisible layers or elements are skipped.

[tests.zip](https://github.com/evil-mad/axidraw/files/1585052/tests.zip)

**Comment by oskay** [comment]
It looks like Inkscape currently uses `display:none` to indicate hidden objects, rather than the "visibility" mechanism. However, the SVG spec does support both. 

It is probably not tractable to be able to handle absolutely _all_ cases and weights for different selectors -- CSS is vast and unwieldy -- but basic support seems essential. 

Starting with your example, I put together a test file that has very lightly nested display/visibility styles. (It does not display all possible cases, only some very simple ones.)  

Case in point about not handling all cases, Inkscape does not handle these in the same ways as Chrome/Safari/Firefox/Illustrator, which all display it in the same way.

Here is how Chrome/Safari/Firefox/Illustrator display the file:
<img width="739" alt="screen shot 2017-12-24 at 3 55 35 pm" src="https://user-images.githubusercontent.com/1009180/34329802-1467d686-e8c3-11e7-9a05-2d09cca71015.png">

And, here is how Inkscape displays the file:
<img width="1036" alt="screen shot 2017-12-24 at 3 57 31 pm" src="https://user-images.githubusercontent.com/1009180/34329803-37381266-e8c3-11e7-83f9-349554267f1b.png">

As for which we should be doing, I really don't know the best answer to that. Our party line thus far has been to try to replicate the behavior of Inkscape since it should be able to show the user what we _expect_ plotting to look like, but this seems like a bug in Inkscape.

Yes: Here are the relevant bug reports from Inkscape:
https://bugs.launchpad.net/inkscape/+bug/1577763
https://bugs.launchpad.net/inkscape/+bug/166042


Based on these behaviors, it appears that:
* display:none should cause an object [and its children](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/display) to not be displayed, regardless of whether or not one of them contains an assertion to the contrary.
* The visibility attribute can be overridden.

This verifies (as expected) that the visibility attribute needs to be passed down through the recursive parsing of the SVG/XML tree, but that display does not need to be.



[hiddenExample.zip](https://github.com/evil-mad/axidraw/files/1585124/hiddenExample.zip)

**Comment by MartyMacGyver** [comment]
Except for renaming 'v' to something more Pythonic, I didn't change the 'visibility' logic. However, I did add the logic necessary to correctly handle `display:none` in a cascading fashion (replicating the behavior of Inkscape (and Illustrator) for hidden objects) so it should be sound.

**Comment by oskay** [comment]
No; The `parent_displayable=displayable` that you are passing down is unnecessary, because `display:none` cannot be overridden.

**Comment by MartyMacGyver** [comment]
Right... which means any lower layers that get processed need to short-circuit if their parent has that attribute. I followed the pattern used for 'visibility' in that regard.

Or are you saying we can simply not pass it along and short-circuit on a given element? Will that have the same effect?

**Comment by MartyMacGyver** [comment]
I simplified the code (seems to be no change in how it ends up working) and updated the branch accordingly.

**Comment by oskay** [comment]
We simply _should not_ recursively parse any deeper if the object has `display:none` set. 

Also, I'm still reading up on this. We need to handle both the SVG attributes as well as the CSS attributes, which may even conflict with one another. It's just not that straightforward. 

Also: Renaming a variable may be fine, but it should be a separate (tiny) pull request to do that. I'd actually oppose that particular change, because using `visibility` as a variable name to keep track of the state of the SVG and/or CSS `visibility` attributes _does not_ improve clarity.

I'm attaching a second test file that uses the display and visibility attributes directly, rather than styles. It renders the same as the other file in both browsers and Inkscape, however the existing logic for the visibility does work in some of the circumstances. (The existing visibility logic only looks at the visibility attribute, not the style.)

[hiddenExample2.zip](https://github.com/evil-mad/axidraw/files/1585181/hiddenExample2.zip)

**Comment by MartyMacGyver** [comment]
There's whole raft of pep8 / flake8 cleanups that should be happening in this file - I tend to clean things up as I encounter them in code I touch, especially something as blatant as single-character variable names like that, but feel free to ignore them. The variable is only for the `visibility` attribute so it seems logical (I'm not sure what else `v` is supposed to stand for except that, and it tracks with the `parent_visibility` variable it directly relates to).

If you look at the current changes, I'm not overloading that variable regardless, just naming it consistently and Pythonically. Is there an issue with my handling of `display:none` at this point, given the current changes? I would expect `display:none` to supercede `visibility` in any case.

**Comment by oskay** [comment]
Regardless of how good of an idea they might be, _my_ personal preference is that style changes be added separately, so that it's straightforward to identify functional changes in the diffs. 

(We could definitely have a discussion about what it means for an internal variable name to be pythonic in a case like this, if that's what you want. But it really should be a separate issue/pr. My reading is that PEP8 explicitly allows single character variable names so long as they aren't hard to read or easy to confuse. And, if your guidance is that to be consistent and pythonic, one should directly name a variable identically to an attribute that it represents, consistency would also require that the new variable be named "style" rather than "display_style".  This kind of bikeshedding is why I don't like mixing style changes with functional changes. It's often easy to say "yes" or "no" to a pull request about a single thing, and never easy when it combines unrelated changes.)

As for the actual issue, here is a slightly better way. The following snippet catches a few other possible ways that `display:none` could be formatted, and accomplishes the task (at least for the CSS variant):

```
			style = simplestyle.parseStyle(node.get("style"))
			if "display" in style.keys() and style["display"] == "none":
				continue	# Do not plot this object nor its children
```

This does give a _very large_ change to the overall behavior, and not one that I had really absorbed until testing it. Up to now, we have (very intentionally) plotted all selected layers, even if they were not visible to the user. With this change, not only do you need to select the layers to print, but also make sure that they are visible. While quite different, I think that this change is on balance a net positive, as it does increase the similarity to the print function.

**Comment by MartyMacGyver** [comment]
If it wasn't easy to confuse I wouldn't have changed it, but it's your call. As for the code above, that probably works too (I'll give it a try when I have time).

As for the current behavior of rendering / printing hidden layers and ignoring the display attribute, it may be intentional (though why? Did Inkscape not support standard layers before?) but it's quite different from any other app with that functionality. Even Inkscape doesn't render its own hidden layers. It seems less like a big change and more like fixing a big bug to me.

Making sure layers are visible is trivial with a cursory inspection of the file (if I open a file and layers aren't visible I wouldn't expect them to render). I'd argue that the `visibility` variable is the more cryptic one as it's not clear how that looks or renders in Inkscape, etc., but that's not what's at issue here.

As for the method of selecting layers to print by changing their names to fit a constrained numeric naming convention, that's hardly trivial. One alternative is to hide the layers you don't want to print, right in the standard Inkscape (or Illustrator) UI, which is the focus of this report. One could also select the specific (and I'd argue, visible) layer in the AxiDraw control UI by its given name without needing to rename it (versus the existing number dial). I'm not sure if that would work as I envision it given Inkscape constraints but I think it just might.

**Comment by oskay** [comment]
The numbered layers system works quite well, and offers a lot of functionality above and beyond the obvious: http://wiki.evilmadscientist.com/AxiDraw_Layer_Control

This change may actually be disruptive to that, as it requires that you also check which layers are visible before plotting.

**Comment by MartyMacGyver** [comment]
It may be a creatively contrived system, but it is at odds with what a user would normally expect a hidden layer to do (namely, not print or plot). The purpose ought to be extended functionality where no standard solution exists, not unexpected behavior.

**Comment by oskay** [comment]
Ouch. 

I have already agreed that this is a good way forward.

However, the current software does behave _as expected_ and as documented-- plotting all layers, not just selected layers. We will have to make changes to the documentation in the future to accommodate this change.

**Comment by MartyMacGyver** [comment]
Sorry, it sounded like this was on its way to being "works as designed"-ed. I didn't think this would be disruptive and I don't really think it will be... Do people really hide layers in the UI and still expect them to print? I would think if anything people are either printing all layers and not manually hiding them in the first place (perhaps because it has no effect currently), or they are printing only specific layers. Things to ponder...

**Comment by oskay** [comment]
I don't think that it will be a problem, so long as we update the documentation at the same time.

The primary way that layers are used is for managing multicolor plots.

We have been using this UI metaphor on thousands of machines since 2010, and this is (so far as I know) the first time that someone has described this behavior as "unexpected."

**Comment by MartyMacGyver** [comment]
I understand the purpose - in fact, that's why I was dabbling with hiding layers. From the perspective of the UI primitives one has available in the editor itself (specifically hiding/showing output layers) it's unexpected. I was honestly surprised when layers I'd hidden were still being plotted by default.

**Comment by MartyMacGyver** [comment]
I've updated the code on my branch accordingly, with your suggested code changed above.
