### ISSUE TITLE
Pen "up" x/y direction

### ISSUE THREAD

**Issue by simlu** [evil-mad/axidraw#64]
Currently the behaviour is that the pen will immediately go to the next point from the current finish point. If the wait on pen up option is set to 0ms, this causes a tiny line to be drawn into the direction of the next point.

We're fine with that, however would prefer if there was an option to 'continue movement into current direction until pen is up', so that the line continuation feels more natural.

Alternative to the option would be to allow ghost dots that the machine has to go to without actually doing any pen up /down movements.

Any suggestions how this could be supported in the code and where to look at to implement this?

Thank you very much for the continued support! L~

**Comment by oskay** [comment]
> If the wait on pen up option is set to 0ms, this causes a tiny line to be drawn into the direction of the next point.

No-- that is not the intent, and it is not true in most cases. 

There should *never* be a little line in the direction of the next point. If there is, then something needs to be adjusted. In most cases, this means that either the vertical pen position is not appropriate or the vertical range is not selected properly.

The vertical range should be adjusted until there is about, or a little less than, 1/4 inch (6 mm) vertical travel between the two positions. The pen should be inserted with the pen in the "up" position, about 1/8 to 1/4 inch (3-6 mm) above the paper.

With this kind of setup, if you're still getting the pen dragging on the paper when it shouldn't, you may need to decrease the pen-lift speed setting, raise the pen-up height, or further adjust up the physical position of the pen when at the pen-up setting.

In case of unusual setups, cases where there is zero pen-lift distance, or certain other setups, we do have an optional delay to add there as well. But in a typical AxiDraw setup, properly adjusted, that setting should _always_ be 0 ms. Adding a delay there to compensate for an otherwise improper setup tends to just add an unnecessary time delay. We have considered removing these optional delays, but they do seem to be helpful for certain setups-- we may move them to a configuration file in the future.

----

To answer your question (which is not really related to the issue that you're having), there is no straightforward way to do that. Easing the pen down to start the line and following through at the end would essentially require modifying the input paths to add an extension to both sides, and calculating when to issue the commands to raise/lower the pens that correspond to specific times along the path, rather than at the ends of the paths. That's not too difficult when plotting with constant speed, but it's not too easy with acceleration added in.

As the absolute position at which the pen contacts the paper depends on the physical position of the pen, the sizes of these tails at the start and end would be vastly more (not less) sensitive to the exact position of the pen in the holder. The best approach would be to make the pen-up pen-down moves very fast to go sharply up and down, so as to make the tails as short and well-defined as possible.

Handling the various special cases that occur would be challenging.

As one example, think about clipping the curves at the edges of the paper. Clipping would need to occur not at the edge of the paper, but at different times and positions depending on the angle at which each potentially clipped curve path intersects the edge of the paper. Imagine complex curves that repeatedly exceed the edges of the paper -- presently we can just clip them as they intersect the edge. With ramping up and down at the edges, I think that there could be cases where curve sections that otherwise would be plotted would need to be completely removed. 

As a second example, consider a document with many dots in it (maybe, a period at the end of a sentence or a stipple drawing). With tails added to the beginning and end, every dot becomes a stroke on the page, not a dot. That brings us back to the thing that you were complaining about: Extra tails on every stroke.

See also related issues:
https://github.com/evil-mad/axidraw/issues/56
https://github.com/evil-mad/EggBot/issues/101
