### ISSUE TITLE
Is it possible to further limit the limits of travel?

### ISSUE THREAD

**Issue by sbauer322** [evil-mad/axidraw#84]
For this situation, I have the snazzy [Magnetic Easel for AxiDraw - Letter/A4](https://shop.evilmadscientist.com/productsmenu/913) along with the AxiDraw V3. 

When in interactive mode, is there way to configure the Axidraw to prevent it from going off the edge of the easel? I suppose, in other words, is there a config to shrink the drawing boundary?

**Comment by oskay** [comment]
The effective drawing area of the Letter/A4 magnetic easel, assuming that you have paper bounded by the rulers, is nominally 300.3 x 219.2 mm.

The travel limits set by the configuration file for the V3 are:
```
x_travel_default = 11.81  # AxiDraw V2 and AxiDraw V3: X Carriage travel in inches.     Default: 300 mm = about 11.81 inches
y_travel_default = 8.58   # AxiDraw V2 and AxiDraw V3: Y Carriage travel in inches.     Default: 218 mm = about 8.58 inches
```

You can edit these values in the configuration file. You might want to change them to limit (for example) to the paper size that you use, rather than the machine travel limits.

Alternately, use the [`params` feature](https://axidraw.com/doc/py_api/#additional-parameters) to change these values in your python program.

```
from pyaxidraw import axidraw  
ad = axidraw.AxiDraw()
ad.interactive()
ad.params.x_travel_default = 6.0
ad.params.y_travel_default = 3.0
ad.connect()
[...]
```

**Comment by sbauer322** [comment]
This is exactly what I was looking for. I'll give it a try tonight.

Thank you!

**Comment by sbauer322** [comment]
Yep, your recommendation worked perfectly - thanks again!
